branches:
  only:
    - master

language: node_js

os:
  - linux

sudo: false

services:
  - docker

node_js:
  - "12"
  - "10"
  - "8"

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

git:
  depth: 1

install:
  - npm install
  - npm install coveralls --save-dev

before_script:
  - npm run build;

script:
  - npm run nyc-ci

after_success:
  - npm run coverage
  - npm pack
  - 'if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_NODE_VERSION" == "8" ]; then
      docker build -t rcjsuen/dockerfile-utils . || travis_terminate 1;
      docker tag rcjsuen/dockerfile-utils rcjsuen/dockerfile-utils:$TRAVIS_COMMIT || travis_terminate 1;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" || travis_terminate 1;
      docker push rcjsuen/dockerfile-utils:latest || travis_terminate 1;
      docker push rcjsuen/dockerfile-utils:$TRAVIS_COMMIT || travis_terminate 1;
    fi'
